### ISSUE TITLE
教学网的按钮莫名冒出了几个哲学符号（？？）

### ISSUE THREAD

**Issue by hexx-k** [zhuozhiyongde/PKU-Art#1]
![1](https://user-images.githubusercontent.com/80234864/143684879-cdca425a-9272-4171-917a-74a606363ed1.png)
如图所示，太怪了（
（Windows 11，MS Edge 96.0.1054.34）

**Comment by zhuozhiyongde** [comment]
哇靠 这是什么
我设置的:after伪类的内容是"\b"啊，被解析错了？
我待会试着改为&nbsp吧

**Comment by zhuozhiyongde** [comment]
已修复 稍后更新

**Comment by zhuozhiyongde** [comment]
已更新，修复此bug
具体排查出的原因是，伪元素在初版设置了 "content:'\b'" 语句，在Safari上是不会显示的，但是在其他浏览器上则会有显示。
目前已通过改为 "content:''" 或设置 "color:rgba(0,0,0,0)" 修复。
