### ISSUE TITLE
[bug] failed to download videos

### ISSUE THREAD

**Issue by ADreamLeft** [zhuozhiyongde/PKU-Art#11]
windows上edge插件更新到2.3.35版本后在下载视频时遇到一些问题：下载进度为100%后，仍然寻找不到目标文件本地所在位置，等待5min后仍无反应

**Comment by zhuozhiyongde** [comment]
尝试更新到最新的 2.3.38 版本试试。 2.3.38 版本更换了 GM API

**Comment by zhuozhiyongde** [comment]
> windows上edge插件更新到2.3.35版本后在下载视频时遇到一些问题：下载进度为100%后，仍然寻找不到目标文件本地所在位置，等待5min后仍无反应

hey，我想知道是否有改变？如果已经正常，我将关闭此 issue。

**Comment by ADreamLeft** [comment]
抱歉，前几天check邮箱时错过了您的邮件。之前发现有点问题后降低了版本，现在再次更新后已经可以正常使用，感谢学长的付出。



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 28, 2024 11:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhuozhiyongde/PKU-Art] [bug] failed to download videos (Issue #11)




  
windows上edge插件更新到2.3.35版本后在下载视频时遇到一些问题：下载进度为100%后，仍然寻找不到目标文件本地所在位置，等待5min后仍无反应
  
hey，我想知道是否有改变？如果已经正常，我将关闭此 issue。

**Comment by zhuozhiyongde** [comment]
![image](https://github.com/zhuozhiyongde/PKU-Art/assets/36695271/45d9ca38-313a-4d59-a68d-edc0784958af)
