### ISSUE TITLE
关于下载失败的问题

### ISSUE THREAD

**Issue by Decmofofs** [zhuozhiyongde/PKU-Art#15]
近期教学网的视频接口似乎又有变动，使用Latest Realease，对任何课程进行下载均失败

**Comment by zhuozhiyongde** [comment]
已知问题，考完简量可能修

**Comment by ADreamLeft** [comment]
作者您好，好像有另一位同学已经做了类似的工作，不过不是插件，是一个下载的网址，或许您能有什么办法联系上他，和他交流一下省去造轮子的时间，网址是https://leohlee.github.io/pkuVideo.html，来源是树洞6333068

**Comment by zhuozhiyongde** [comment]
在 https://github.com/zhuozhiyongde/PKU-Art/commit/fd089dc1721a98815cd553fba8f2c69f90a7bbfd 中修复。

本来就是好的，只是接口变化导致前面的计算 hash 文件名失败了，直接抛出异常跳过了后续计算了。
