### ISSUE TITLE
使用JavaScript注入似乎存在问题

### ISSUE THREAD

**Issue by kekeandzeyu** [zhuozhiyongde/PKU-Art#19]
我在使用PKU Art的时候发现一个很小的问题，当我点击进入课程后点击几次左侧功能区的选项后就会出现似乎是样式冲突，如下图12所示，正常情况下是图3样式。

下面的图片是我在发现问题后尝试点击了几次左侧的选项后得到的图像，其余的按钮都没有动。我使用的是Google Chrome v131.0.6778.140，用TamperMonkey实现的注入。

我自己没有想明白是为什么，会不会是TamperMonkey在注入时的问题？麻烦学长了~

![prob1](https://github.com/user-attachments/assets/b706ef53-c114-41b9-ad41-22d7f4d12fc0)
![prob2](https://github.com/user-attachments/assets/dc32f384-6dc2-40f8-b340-f676ee6ae6d9)
![prob3](https://github.com/user-attachments/assets/191ecf0b-e416-4457-9b61-3639e55e7a62)

**Comment by zhuozhiyongde** [comment]
出现之后刷新会解决问题吗？会的话应该就是缓存没跟上（我猜

**Comment by kekeandzeyu** [comment]
> 出现之后刷新会解决问题吗？会的话应该就是缓存没跟上（我猜

刚刚又折腾了一下出现这样的情况，刷新很多次了似乎不起效果，但是我觉得您说的大概是对的，应该是缓存没跟上的问题)

**Comment by kekeandzeyu** [comment]
> 出现之后刷新会解决问题吗？会的话应该就是缓存没跟上（我猜

抱歉刚才没发现，这个问题越来越奇怪了。我仔细又观察了一下，左边的侧边栏当我把鼠标放在上面时，字体会从黑色变成红色，同时下面会出现横线的delay效果，似乎意味着注入了但是不完全成功？

**Comment by zhuozhiyongde** [comment]
> > 出现之后刷新会解决问题吗？会的话应该就是缓存没跟上（我猜
> 
> 抱歉刚才没发现，这个问题越来越奇怪了。我仔细又观察了一下，左边的侧边栏当我把鼠标放在上面时，字体会从黑色变成红色，同时下面会出现横线的delay效果，似乎意味着注入了但是不完全成功？

录个屏？cmd/ctrl + shift + i 看一眼控制台有无信息

**Comment by zhuozhiyongde** [comment]
听上去像是加载顺序的原因，但我这边工作正常

**Comment by kekeandzeyu** [comment]
现在我注意到主要集中在点击“答疑讨论”的时候会出现这个问题(尽管平时也不用这个功能hhh
![屏幕截图 2024-12-16 220529](https://github.com/user-attachments/assets/b5e5b22d-6abe-4317-b24c-6a3018304c03)

**Comment by zhuozhiyongde** [comment]
哦这样，那可能是正常的，没适配这个页面
