### ISSUE TITLE
教学网对宽屏幕支持有问题

### ISSUE THREAD

**Issue by fishiu** [zhuozhiyongde/PKU-Art#3]
问题不严重，但是如果能改一下就更好啦
![jl9nxI](http://pic.fishiu.com/uPic/jl9nxI.jpg)

**Comment by zhuozhiyongde** [comment]
这可能是因为我使用了绝对像素单位导致的问题
这个bug可能在不同设备上呈现出来的程度不一样，我会尽量抽时间出来修复
稍后我会给出一个暂时的解决方法

**Comment by zhuozhiyongde** [comment]
暂时的解决方法：
请将`courseHomePage`（或`Section8`）的第246行的`left`的值更改为·20%·
预计周三发布修复（最近DDL太多了

**Comment by zhuozhiyongde** [comment]
已更新
请从Stylish/GreesyFork/Github Releases下载最新版本
