### ISSUE TITLE
教学网过渡动画时长偏长，影响用户交互

### ISSUE THREAD

**Issue by wongsingfo** [zhuozhiyongde/PKU-Art#4]
这个项目非常有针对性和创意，学校的网站样式设计确实难以恭维。我有一个建议，希望能帮这个项目做得更好。

我在 course.pku.edu.cn 试用时，觉得元素进入的场景的时间过长（即 navigation bar 从左侧滑入，body 从下面滑入两个动画），这非常影响用户交互，特别是每次进入新的页面都要重播一次动画。可以考虑移除该动画。

相关的设计理论和设计参考：https://material.io/design/motion/speed.html#controlling-speed

**Comment by zhuozhiyongde** [comment]
这个问题之前就发现了，在最新版本应该只有教学网的首页会加载动画，而所有子界面应该只有Body的滑入没有导航栏的加载。
如果需要禁用所有动画，我考虑稍后在Stylish上更新一个带禁用动画选项的版本。
