### ISSUE TITLE
窗口比例变化将导致课程内页面左侧菜单栏消失

### ISSUE THREAD

**Issue by Brianwind** [zhuozhiyongde/PKU-Art#6]
在浏览器窗口最大化模式下没有问题，但是一旦选择窗口化等方式将浏览器页面比例变窄，课程内部的左侧菜单栏将不可见，必须关闭浏览器并重新进入才可以显示出来。
Tampermonkey版本 Windows11  Edge浏览器

**Comment by zhuozhiyongde** [comment]
这是隐藏了左侧puller带来的副作用。教学网可能对左侧菜单的状态做了存储，并且一旦窗口宽度小于某个值后就会让左侧面板收起。因为隐藏了左侧puller，所以这个东西并不能复原，必须重新刷新窗口（可以是新建标签页or退出重进等方式）才会复原。
我认为这个问题是可以解决的，比如选择显示puller或者找到相应的伸缩css加以覆盖。稍后我会更新一个版本来解决这个问题。

**Comment by zhuozhiyongde** [comment]
一个临时的解决方案是，出现收起后暂时禁用PKU Art，随后刷新页面重新使用puller展开，然后再启动PKU Art。

**Comment by Brianwind** [comment]
感谢！

**Comment by zhuozhiyongde** [comment]
请更新至最新的JavaScript版本，此问题已解决。
