### ISSUE TITLE
教学网课程号含有字母时无法识别消除

### ISSUE THREAD

**Issue by zyt600** [zhuozhiyongde/PKU-Art#7]
![截屏2023-04-08 16 50 21](https://user-images.githubusercontent.com/61863235/230712801-ecf2ddcb-2967-43b4-8555-f5cba6ff5136.png)

**Comment by zyt600** [comment]
其他课程号例如1234-12344321-232可以消除，但形如12313-1313a的不行

**Comment by zhuozhiyongde** [comment]
可以直接留个完整的课名吗 我现在的逻辑是对数字进行正则匹配来着，如果你能提供一个完整的样例，我想问我应该能很快修复。

**Comment by zyt600** [comment]
是22232-00038-03835950-w高级英语口语(22-23学年第2学期)     (如图）


 周雨童
 ***@***.***
  




---- 回复的原邮件 ----
发件人  ***@***.***> 发送日期  2023年04月8日 20:10 收件人  ***@***.***> 抄送人  ***@***.***> ,
 ***@***.***> 主题  Re: [zhuozhiyongde/PKU-Art] 教学网课程号含有字母时无法识别消除 (Issue #7)  

可以直接留个完整的课名吗 我现在的逻辑是对数字进行正则匹配来着，如果你能提供一个完整的样例，我想问我应该能很快修复。

**Comment by zhuozhiyongde** [comment]
很奇怪，我和本部别的本科同学对了一下，我们的课表都是形如
`22232-10891-89130076-0016174072-11-1: 医学遗传学(22-23学年第2学期)`
这样的课程，而你的课程一个是标识的长度不对，一个是没有`:`冒号作为分割，感觉不是很好判断后处理。
我猜测这可能和年级（本科or研究生）或者是否为重修课程（w）有关，可能需要收集更多的样例，当然如果你知道原因的话，也欢迎回复，感谢！

**Comment by zyt600** [comment]
我是本科大三年级；曾经退过课，如图中的人工智能引论，但这门课的显示正常；本次出现w的课是我首次选课，并且目前并非退课季，我也并未退课。在关闭插件后，显示如图2，我也有冒号😂很神奇，我猜测一个匹配解决方案是     .*:


 周雨童
 ***@***.***
  




---- 回复的原邮件 ----
发件人  ***@***.***> 发送日期  2023年04月8日 20:28 收件人  ***@***.***> 抄送人  ***@***.***> ,
 ***@***.***> 主题  Re: [zhuozhiyongde/PKU-Art] 教学网课程号含有字母时无法识别消除 (Issue #7)  

很奇怪，我和本部别的本科同学对了一下，我们的课表都是形如
 22232-10891-89130076-0016174072-11-1: 医学遗传学(22-23学年第2学期)
 这样的课程，而你的课程一个是标识的长度不对，一个是没有:冒号作为分割，感觉不是很好判断后处理。
 我猜测这可能和年级（本科or研究生）或者是否为重修课程（w）有关，可能需要收集更多的样例，当然如果你知道原因的话，也欢迎回复，感谢！

**Comment by zhuozhiyongde** [comment]
抱歉，你的图片并未成功加载，建议你在Github上上传
如果你有冒号的话，那就简单了，直接匹配到第一个冒号之前就行

**Comment by zyt600** [comment]
不好意思，我之前都是回复邮件，没想到图片没传上来

22232-00038-03835950-w201600370-00-1: 高级英语口语(22-23学年第2学期)
22232-00086-00333360-0006172261-00-1: 魅力机器人(22-23学年第2学期)

上述两条分别是异常和正常的，我认为匹配到英文引号可以解决问题

![截屏2023-04-08 21 05 13](https://user-images.githubusercontent.com/61863235/230722727-186288c3-ca1d-4366-8b24-a654531e51c5.png)
![截屏2023-04-08 20 29 49](https://user-images.githubusercontent.com/61863235/230722735-b2592842-f9df-4400-9efc-4300ee1b8f49.png)

**Comment by zhuozhiyongde** [comment]
PKU Art v2.3.18 JavaScript 版本已修复此问题。

**Comment by zyt600** [comment]
谢谢！
