### ISSUE TITLE
[bug] homework submission comment field color problem(dark mode?)

### ISSUE THREAD

**Issue by sjfhsjfh** [zhuozhiyongde/PKU-Art#8]
<img width="1054" alt="图片" src="https://github.com/zhuozhiyongde/PKU-Art/assets/58244206/18209bef-5792-4a7b-8da3-f57920b1fcdf">

at course.pku.edu.cn/webapps/assignment/uploadAssignment

Firefox 117.0.1 (64 位)
M1 Macbook Pro

is this expected?

I'm using [Darkreader](https://darkreader.org/) but not activating the plugin when the screenshot was taken

**Comment by zhuozhiyongde** [comment]
我现在没有要交作业的课程，暂时无法debug。
但我好像记得这不是PKU Art的问题，是因为教学网引入了Tiny这个富文本编辑器的原因，其中样式我不太好越级覆盖。

**Comment by zhuozhiyongde** [comment]
经排查，这个错误是由于富文本编辑器Tinymce的原因，如果想要更改其样式需要使用JS对页面进行较大的改动，故不予支持。
