### ISSUE TITLE
[bug] Grade - detailed items overflow

### ISSUE THREAD

**Issue by sjfhsjfh** [zhuozhiyongde/PKU-Art#9]
## What happend 问题描述

<img width="316" alt="图片" src="https://github.com/zhuozhiyongde/PKU-Art/assets/58244206/11ae90ba-e466-45ff-a9bf-63deda50eec9">

如图所示，成绩详细信息（class 为 `itemStats`）部分超出父元素范围

## Possible fix 建议方案

- 横向排列, 把更多信息罗列在成绩右侧, 作为级别不同于 `pointsPossible clearfloats` 的元素展示
- 加个 info 的 icon svg, 更多信息修改为悬浮显示? (我觉得这个可行一点, 不知教学网怎么写的, 这个详细信息的数量应该是不定的吧, 这样处理应该可以让界面有一些一致性)

**Comment by zhuozhiyongde** [comment]
找了一门上学期的高数课，确实可以复现。

预计年后修复，最近比较忙orz

**Comment by zhuozhiyongde** [comment]
Closed in 2b203c7423b8b1fb87325a91a5aaf4c1f5c5bb23
